almadecolibri/urls.py
# Django Imports
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

# Project Imports
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inicio.urls')),
    path('productos/', include('productos.urls')),
    path('shop/', include('tienda.urls')),
    path('contacto/', include('contacto.urls')),
    path('register/', include('registro.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

inicio/urls.py
# Django Imports
from django.urls import path

# App Imports
from . import views


urlpatterns = [
    path('',views.inicio, name="Inicio"),
]

productos/urls.py
# Django Imports
from django.urls import path

# App Imports
from . import views


urlpatterns = [
    path('',views.productos, name="Productos"),
    path('<int:param>/', views.productos),
]

productos/models.py
# Django imports
from django.db import models

# Proyect Import

class Producto(models.Model):
    """ Carga de los productos a la base de datos.
    
    Contiene: 
    Nombre del Producto.
    Precio.
    Categoria (Heredada de la clase Categoria_prod)
    Imagen (se debe tener importada la libreria Pillow)
    Costo (costo del producto, campo creado con el fin de 
            realizar estadisticas de costo / ganancia)
    """
    nombre_prd = models.CharField(max_length=30, verbose_name="Nombre Producto")
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    id_categoria = models.ForeignKey('Categoria_prod', on_delete=models.CASCADE, verbose_name="Categoria")
    imagen_prd = models.ImageField(upload_to = 'productos', blank=True)
    costo = models.DecimalField(max_digits=10, decimal_places=2, blank=True, default=0.0)

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

    def __str__(self):
        return self.nombre_prd

class Categoria_prod(models.Model):
    """ Clase con las categorias existentes para todos los productos
    
    Tiene como unico campo la Categoria que luego será importada 
    para usarse en Producto)
    """
    categoria = models.CharField(max_length=15)

    class Meta:
        verbose_name = 'Categoria Producto'
        verbose_name_plural = 'Categoria Productos'

    def __str__(self):
        return self.categoria

productos/forms.py
# Django Imports
from django import forms
from django.forms.widgets import HiddenInput

# Project Imports


class AgregarAlPedido(forms.Form):
    # Formulario para la ventana modal que se abre 
    # al agregar un elemento al carrito de compras.
    cantidad_a_comprar = forms.IntegerField(
        widget=forms.NumberInput(
            attrs= {
                'class': 'form-control',
                'placeholder': 'ej: 100g'
            }
        )
    )
    id_producto = forms.IntegerField(
        widget=forms.HiddenInput(
            attrs= {
                'class':'form-control',
                'value':'0',
                }
            )
        )

productos/views.py
# Django Imports
from django.shortcuts import render
from django.contrib.auth.models import User
from django.db.models import Sum

# Proyect Imports
from productos.models import Producto
from tienda.models import Venta, Detalle_Venta
from productos.forms import AgregarAlPedido


def productos(request,param=0):
    # View que muestra un resumen de los productos ofrecidos
    def realizar_compra(id_usuario, obtener_precio_final, datos_formulario):
        # Obtengo el estado de la ultima venta registrada (si existe)
            crear_venta = Venta.objects.filter(id_usuario = dato_usuario).last()
            if crear_venta != None:
                try:
                    # Primer caso, que crea una venta, 
                    # cuando venta finalizada o procesada están True.
                    if (crear_venta.venta_finalizada == True) and (crear_venta.venta_procesada == True):
                        # Agrego el dato del usuario para que se cree
                        # una nueva venta.
                        
                        venta = Venta(
                            id_usuario = dato_usuario,
                        )
                        venta.save()
                        # Busco la venta recien creada.
                        info_venta = Venta.objects.filter(
                                id_usuario = dato_usuario, 
                                venta_finalizada = False, 
                                venta_procesada = False,
                        ).last()
                        
                        # Luego guardo la compra en la nueva venta.
                        detall_venta = Detalle_Venta(
                            id_venta = info_venta, 
                            id_producto = Producto.objects.get(id=datos_formulario['id_producto']), 
                            cant_vendida = datos_formulario['cantidad_a_comprar'],
                            precio_unitario = obtener_precio_final
                        )
                        detall_venta.save()
                        print(obtener_precio_final)
                        # Agrego el precio a la venta.
                        venta.precio_total += float(obtener_precio_final)
                        venta.save()
                    elif (crear_venta.venta_finalizada == False) and (crear_venta.venta_procesada == False):
                        # Guardola compra en la venta.
                        detall_venta = Detalle_Venta(
                            id_venta = crear_venta, 
                            id_producto = Producto.objects.get(id=datos_formulario['id_producto']), 
                            cant_vendida = datos_formulario['cantidad_a_comprar'],
                            precio_unitario = obtener_precio_final
                        )
                        detall_venta.save()
                        # Agrego el precio a la venta.
                        crear_venta.precio_total += obtener_precio_final
                        crear_venta.save()
                    elif (crear_venta.venta_finalizada == True) and (crear_venta.venta_procesada == False):
                        # Busco si el usuario tiene 
                        # venta finalizada pero no procesada.
                        # Y la cambio a False
                        crear_venta.venta_finalizada = False
                        crear_venta.save()
                        # Agrego el nuevo producto
                        detall_venta = Detalle_Venta(
                            id_venta = crear_venta, 
                            id_producto = Producto.objects.get(id=datos_formulario['id_producto']), 
                            cant_vendida = datos_formulario['cantidad_a_comprar'],
                            precio_unitario = obtener_precio_final
                        )
                        detall_venta.save()
                        # Agrego el precio a la venta.
                        crear_venta.precio_total += obtener_precio_final
                        crear_venta.save()
                    else:
                        print('Error de indice 1')
                except:
                    print('Error de indice 2')
            else:
                venta = Venta(
                    id_usuario = id_usuario,
                )
                venta.save()
                # Busco la venta recien creada.
                info_venta = Venta.objects.filter(
                        id_usuario = id_usuario,
                        venta_finalizada = False,
                        venta_procesada = False,
                ).last()
                # Luego guardo la compra en la nueva venta.
                detall_venta = Detalle_Venta(
                    id_venta = info_venta,
                    id_producto = Producto.objects.get(id=datos_formulario['id_producto']),
                    cant_vendida = datos_formulario['cantidad_a_comprar'],
                    precio_unitario = obtener_precio_final
                )
                detall_venta.save()
                # Agrego el precio a la venta.
                venta.precio_total += obtener_precio_final
                venta.save()
    def realizar_compra_invitado(id_usuario, obtener_precio_final, datos_formulario):
        request.session['usuario'] = str(User.objects.get(username= 'invitado'))
        crear_venta = Venta.objects.filter(id_usuario = id_usuario, nombre_inv = request.session.session_key).last()
        print(crear_venta)
        if crear_venta != None:
            try:
                # Primer caso, que crea una venta, 
                # cuando venta finalizada o procesada están True.
                if (crear_venta.venta_finalizada == True) and (crear_venta.venta_procesada == True):
                    print('picaña1')
                    # Agrego el dato del usuario para que se cree
                    # una nueva venta.
                    
                    venta = Venta(
                        id_usuario = id_usuario,
                        nombre_inv = request.session.session_key,
                    )
                    venta.save()
                    # Busco la venta recien creada.
                    info_venta = Venta.objects.filter(
                            id_usuario = id_usuario,
                            nombre_inv = request.session.session_key, 
                            venta_finalizada = False, 
                            venta_procesada = False,
                    ).last()
                    
                    # Luego guardo la compra en la nueva venta.
                    detall_venta = Detalle_Venta(
                        id_venta = info_venta, 
                        id_producto = Producto.objects.get(id=datos_formulario['id_producto']), 
                        cant_vendida = datos_formulario['cantidad_a_comprar'],
                        precio_unitario = obtener_precio_final
                    )
                    detall_venta.save()
                    # Agrego el precio a la venta.
                    venta.precio_total += float(obtener_precio_final)
                    venta.save()
                elif (crear_venta.venta_finalizada == False) and (crear_venta.venta_procesada == False):
                    print('picaña2')
                    # Guardola compra en la venta.
                    detall_venta = Detalle_Venta(
                        id_venta = crear_venta, 
                        id_producto = Producto.objects.get(id=datos_formulario['id_producto']), 
                        cant_vendida = datos_formulario['cantidad_a_comprar'],
                        precio_unitario = obtener_precio_final
                    )
                    detall_venta.save()
                    # Agrego el precio a la venta.
                    crear_venta.precio_total += obtener_precio_final
                    crear_venta.save()
                elif (crear_venta.venta_finalizada == True) and (crear_venta.venta_procesada == False):
                    print('picaña3')
                    # Busco si el usuario tiene 
                    # venta finalizada pero no procesada.
                    # Y la cambio a False
                    crear_venta.venta_finalizada = False
                    crear_venta.save()
                    # Agrego el nuevo producto
                    detall_venta = Detalle_Venta(
                        id_venta = crear_venta, 
                        id_producto = Producto.objects.get(id=datos_formulario['id_producto']), 
                        cant_vendida = datos_formulario['cantidad_a_comprar'],
                        precio_unitario = obtener_precio_final
                    )
                    detall_venta.save()
                    # Agrego el precio a la venta.
                    crear_venta.precio_total += obtener_precio_final
                    crear_venta.save()
                else:
                    print('Error de indice 1')
            except:
                print('Error de indice 2')
        else:
            venta = Venta(
                id_usuario = id_usuario,
                nombre_inv = request.session.session_key,
            )
            venta.save()
            # Busco la venta recien creada.
            info_venta = Venta.objects.filter(
                    id_usuario = id_usuario, 
                    nombre_inv = request.session.session_key,
                    venta_finalizada = False, 
                    venta_procesada = False,
            ).last()
            # Luego guardo la compra en la nueva venta.
            detall_venta = Detalle_Venta(
                id_venta = info_venta, 
                id_producto = Producto.objects.get(id=datos_formulario['id_producto']), 
                cant_vendida = datos_formulario['cantidad_a_comprar'],
                precio_unitario = obtener_precio_final
            )
            detall_venta.save()
            # Agrego el precio a la venta.
            venta.precio_total += obtener_precio_final
            venta.save()

productos/templates/productos/productos.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1 class="text-center" style= "color: white;">PRODUCTOS</h1>
</div>
<br>
<div class="container barrafiltro">
  <ul class="nav justify-content-center">
    <li>
      <form class="form-inline" type="get" action="." style="margin: 0">
        <label style="padding-right:0.3cm;" for="">BUSQUEDA DE PRODUCTO</label>
        <input class="form-control mr-sm-2" id="search_box" type="search" name="search_box" placeholder="Ej: Almendra" >
        <button id="search_submit" type="submit" class="btn btn-outline-success my-2 my-sm-0" >Buscar</button>
      </form>
    </li>
    <form class="form-inline" type="get" action="." style="margin: 0">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" style="color: white" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">ORDENAR</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="/productos/1/">Precio</a>
          <a class="dropdown-item" href="/productos/2/">Categoria</a>
          <a class="dropdown-item" href="/productos/3/">Mas Vendidos</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="/productos/0/">Restaurar orden</a>
        </div>
      </li>
    </form>
  </ul>
</div>
{% if not user.is_authenticated %}
  <div class="container text-center" style="padding: 0px;">
    <div class="alert alert-primary" role="alert">
      Recordá <a href="{% url 'Register' %}" class="alert-link">registrarte</a> para obtener un 10% de descuento en tu priemra compra.
    </div>
  </div>
{% endif %}



<br>

<div class="container">
{% for producto in productos %}
  {% if forloop.first %}
    <div class="row">
  {% endif %}
        <div class="col-md-3 mb-2">
          <!-- Tarjeta Producto -->
          {% include "productos/tarjeta_producto.html" %}
        </div>
        {% if forloop.counter|divisibleby:4 %}</div><div class="row">{% endif %}
          {% if forloop.last %}</div>{% endif %}
{% endfor %}
</div>
{% endblock %}

productos/templates/productos/tarjeta_producto.html
<div class="card" style="width: 100%;">
    <img src="{{ producto.imagen_prd.url }}" class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">{{ producto.nombre_prd }}</h5>
        <p class="card-text">${{ producto.precio }} los 100gr.</p>
        <a type="button" 
            class="btn btn-primary" 
            data-toggle="modal" 
            data-target="#modal{{ producto.id }}">
                Agregar al carrito
        </a>

        <!-- Modal -->

        <div class="modal fade" 
            id="modal{{ producto.id }}" 
            tabindex="-1" 
            role="dialog" 
            aria-labelledby="exampleModalCenterTitle" 
            aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document" id="modal{{ producto.id }}">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Agregar producto:</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form action="" method="POST" target="_self">{% csrf_token %}
                            {% for field in formulario_agregar.visible_fields %}
                                <div class="form">
                                    <div class="row">
                                        <div class="col-md-5 mb-2">
                                            <p>Producto:</p>
                                        </div>
                                        <div class="col-md-6 mb-2">
                                            <p>{{ producto.nombre_prd }}</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-5 mb-2">
                                            <p>Precio por 100g:</p>
                                        </div>
                                        <div class="col-md-6 mb-2">
                                            <p>${{ producto.precio }}</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-5 mb-2">
                                            <label for="{{ field.name }}">
                                                {{ field.label }}
                                            </label>
                                        </div>
                                        <div class="col-md-6 mb-2">
                                            {{ field }}
                                        </div>
                                    </div>
                                {% endfor %}
                                <input 
                                    type="hidden" 
                                    name="id_producto" 
                                    class="form-control" 
                                    value="{{ producto.id }}" 
                                    id="id_id_producto">

                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                                        <button type="submit" class="btn btn-primary">Agregar</button>
                                    </div> 
                                </div>
                        </form>
                    </div>
                    
                </div>
            
            </div>
        </div>
    </div>
</div>

{% block extrajs %}
  

{% endblock extrajs %}